using System.ComponentModel;

namespace BaseCms.Manager.IconsForMenu
{
    public enum MenuIcon
    {
        [Description("fa-adjust")]
        adjust,
        [Description("fa-asterisk")]
        asterisk,
        [Description("fa-ban")]
        ban,
        [Description("fa-bar-chart-o")]
        barChartO,
        [Description("fa-barcode")]
        barcode,
        [Description("fa-flask")]
        flask,
        [Description("fa-beer")]
        beer,
        [Description("fa-bell-o")]
        bellO,
        [Description("fa-bell")]
        bell,
        [Description("fa-bolt")]
        bolt,
        [Description("fa-book")]
        book,
        [Description("fa-bookmark")]
        bookmark,
        [Description("fa-bookmark-o")]
        bookmarkO,
        [Description("fa-briefcase")]
        briefcase,
        [Description("fa-bullhorn")]
        bullhorn,
        [Description("fa-calendar")]
        calendar,
        [Description("fa-camera")]
        camera,
        [Description("fa-camera-retro")]
        cameraRetro,
        [Description("fa-certificate")]
        certificate,
        [Description("fa-check-square-o")]
        checkSquareO,
        [Description("fa-square-o")]
        squareO,
        [Description("fa-circle")]
        circle,
        [Description("fa-circle-o")]
        circleO,
        [Description("fa-cloud")]
        cloud,
        [Description("fa-cloud-download")]
        cloudDownload,
        [Description("fa-cloud-upload")]
        cloudUpload,
        [Description("fa-coffee")]
        coffee,
        [Description("fa-cog")]
        cog,
        [Description("fa-cogs")]
        cogs,
        [Description("fa-comment")]
        comment,
        [Description("fa-comment-o")]
        commentO,
        [Description("fa-comments")]
        comments,
        [Description("fa-comments-o")]
        commentsO,
        [Description("fa-credit-card")]
        creditCard,
        [Description("fa-tachometer")]
        tachometer,
        [Description("fa-desktop")]
        desktop,
        [Description("fa-arrow-circle-o-down")]
        arrowCircleODown,
        [Description("fa-download")]
        download,
        [Description("fa-pencil-square-o")]
        pencilSquareO,
        [Description("fa-envelope")]
        envelope,
        [Description("fa-envelope-o")]
        envelopeO,
        [Description("fa-exchange")]
        exchange,
        [Description("fa-exclamation-circle")]
        exclamationCircle,
        [Description("fa-external-link")]
        externalLink,
        [Description("fa-eye-slash")]
        eyeSlash,
        [Description("fa-eye")]
        eye,
        [Description("fa-video-camera")]
        videoCamera,
        [Description("fa-fighter-jet")]
        fighterJet,
        [Description("fa-film")]
        film,
        [Description("fa-filter")]
        filter,
        [Description("fa-fire")]
        fire,
        [Description("fa-flag")]
        flag,
        [Description("fa-folder")]
        folder,
        [Description("fa-folder-open")]
        folderOpen,
        [Description("fa-folder-o")]
        folderO,
        [Description("fa-folder-open-o")]
        folderOpenO,
        [Description("fa-cutlery")]
        cutlery,
        [Description("fa-gift")]
        gift,
        [Description("fa-glass")]
        glass,
        [Description("fa-globe")]
        globe,
        [Description("fa-users")]
        users,
        [Description("fa-hdd-o")]
        hddO,
        [Description("fa-headphones")]
        headphones,
        [Description("fa-heart")]
        heart,
        [Description("fa-heart-o")]
        heartO,
        [Description("fa-home")]
        home,
        [Description("fa-inbox")]
        inbox,
        [Description("fa-info-circle")]
        infoCircle,
        [Description("fa-key")]
        key,
        [Description("fa-leaf")]
        leaf,
        [Description("fa-laptop")]
        laptop,
        [Description("fa-gavel")]
        gavel,
        [Description("fa-lemon-o")]
        lemonO,
        [Description("fa-lightbulb-o")]
        lightbulbO,
        [Description("fa-lock")]
        llock,
        [Description("fa-unlock")]
        unlock,
        [Description("fa-sitemap")]
        sitemap,
        [Description("fa-file")]
        file,
        [Description("fa-shield")]
        shield
    }
}
