using System;
using System.Collections.Generic;
using System.Reflection;
using BaseCms.CRUDRepository.Core;
using BaseCms.Common.Typograph.Interfaces;
using BaseCms.Common.Validation.Attributes.Base;
using BaseCms.DependencyResolution;
using BaseCms.Views.Detail.Interfaces;
using BaseCms.Views.Link.Attributes;
using BaseCms.Views.List.ListViewMetadata;
using BaseCms.Views.Xml;

namespace BaseCms.Views.Detail
{
    public class DetailMetadataItem
    {
        public DetailMetadataItem(Action<PropertyInfo, object, object, QueryResolver> setter)
        {
            _setter = setter;
            ValidationAttributes = new List<ValidationAttribute>();
        }

        private readonly Action<PropertyInfo, object, object, QueryResolver> _setter;
        public string Label { get; set; }
        public string PropertyName { get; set; }
        public string Format { get; set; }
        public Func<object, object> GetValue { get; set; }
        public ITypeItem ItemType { get; set; }
        public void SetValue(object obj, string value, QueryResolver resolver = null)
        {
            var propInfo = obj.GetType().GetProperty(PropertyName);

            var convertedValue = ItemType.ParseMethod(value);
            if ((AutoTypographMetadata != null) && (convertedValue is string))
            {
                convertedValue = IoC.Container.GetInstance<ITypograph>().ProcessText(convertedValue.ToString(), AutoTypographMetadata.AutoTypographHelperType);
            }

            _setter(propInfo, obj, convertedValue, resolver);
        }

        public bool IsEditable { get; set; }
        public bool IsKey { get; set; }
        public bool IsRequired { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsHidden { get; set; }

        public bool IsHeaderDisplayProperty { get; set; }
        public int MaxLength { get; set; }
        public int Tab { get; set; }
        public int Block { get; set; }

        public int Order { get; set; }
        public LinkMetadata LinkMetadata { get; set; }
        public List<ValidationAttribute> ValidationAttributes { get; set; }
        public DynamicLinkAttribute DynamicLinkViewAttribute { get; set; }
        public ImageMetadata ImageMetadata { get; set; }
        public ListViewMetadata ListViewMetadata { get; set; }
        public HtmlEditorMetadata HtmlEditorMetadata { get; set; }
        //public YandexMetadata YandexMetadata { get; set; }
        public AutoTypographMetadata AutoTypographMetadata { get; set; }
        public XmlEditorMetadata XmlEditorMetadata { get; set; }
        public EditableCollectionMetadata EditableCollectionMetadata { get; set; }
        public PopupMetadata PopupMetadata { get; set; }
    }
}
